version: '3.8'
services:
  app:
    build: .
    env_file:
      - .env
    environment:
      API_PORT: ${API_PORT}
      STAT_PORT: ${STAT_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ENV: ${ENV}
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "${STAT_PORT}:${STAT_PORT}"
      - "${API_PORT}:${API_PORT}"
    command: ["yarn", "${ENV}"]

  db:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./setup.sh:/docker-entrypoint-initdb.d/setup.sh
      - ./db:/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
volumes:
  db-data:
