services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "${STAT_PORT}:${STAT_PORT}"
      - "${API_PORT}:${API_PORT}"
    command: ["pnpm", "${ENV}"]
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - .:/app/db/install.sql
      - .:/app/db/data.sql
      - .:/app/db/structure.sql
    ports:
      - "${DB_PORT}:${DB_PORT}"
